using System;

namespace 입출력개
{
    class Program
    {
        static void Main(string[] args)
        {
            // 문자열로 " 을 출력하고 싶으면 앞에 \를 붙이면 됨.
            Console.WriteLine("|\\_/|");
            Console.WriteLine("|q p|   /}");
            Console.WriteLine("( 0 )\"\"\"\\");
            Console.WriteLine("|\"^\"`    |");
            Console.WriteLine("||_/=\\\\__|");
        }
    }
}